### ISSUE TITLE
Compatibility with webpack

### ISSUE THREAD

**Issue by azavisha** [AoDev/css-byebye#13]
Is there a way to use this with postcss-loader in webpack 4?

**Comment by AoDev** [comment]
@azavisha I haven't used it with the postcss-loader so I can't say anything right now.

Per your comments, it seems a problem with the configuration not being loaded from the external file (postcss.config.js), am I correct? So it does not seem to be a problem with the plugin itself but the Webpack config.

Per the postcss docs, you need to pass a [path to the config file](https://github.com/postcss/postcss-loader#config). Can you show your Webpack config when trying to use an external config file for postcss or better, a fully reproducible example?

**Comment by azavisha** [comment]
@AoDev Yes, the configuration is not being loaded form the external file, but I am certain that this is not a problem with `webpack` or `postcss`, because other `postcss` plugins are working just fine (for example, `autoprefixer`). In addition to this, if the configuration is not provided in the `webpack.config.js`, the build fails because `css-byebye` cannot find the configuration. This probably has something to do with breaking changes introduced in `webpack 4`.

As a side note, the path to the `postcss` config file is not required in `postcss` and not even recommended. It is only needed when you save `postcss.config.js` in some non-standard location.

I used this workaround in `webpack.config.js` to make it work with the main `postcss.config.js` file, but this is not ideal, because there could be multiple `postcss.config.js` files in a single project.

```js
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    plugins: () => [
      require('css-byebye')(require('./postcss.config')['plugins']['css-byebye'])
    ]
  }
}
```

**Comment by AoDev** [comment]
@azavisha I haven't switched to Webpack 4 yet. I can't promise you to fix this soon. I missed the Webpack release but it looks pretty cool per their blog post. I'll pick one of my projects and update it to Webpack 4. Then I'll see if I can use it as test case to fix your issue. That said, a PR is welcomed too ;)

**Comment by azavisha** [comment]
@AoDev It looks like the root of the problem was in the location of my `node_modules` directory. It was located in a sub-folder instead of the root of the project, which was fine in general, but it was apparently causing this particular issue, because when webpack encountered `css-byebye` in `postcss.config.js`, it likely just couldn't resolve the module. Although, strangely, it didn't complain.

Now everything works great even without any options in `webpack.config.js`. I just give webpack the name of the loader (`postcss-loader`) and it automatically finds all `postcss.config.js` files and loads all postcss plugins without issues. Webpack is awesome! Sorry about the false alarm :)

**Comment by AoDev** [comment]
Glad that you could resolve it. I'll close the issue. :)
