### ISSUE TITLE
Update to postcss 8.2.13 or newer to prevent vulnerability

### ISSUE THREAD

**Issue by RiZKiT** [AoDev/css-byebye#20]
`npm audit` it throwing the following issue (https://github.com/advisories/GHSA-566m-qj78-rww5):
```postcss  <8.2.13
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
No fix available
node_modules/css-byebye/node_modules/postcss
  css-byebye  *
  Depends on vulnerable versions of postcss
  node_modules/css-byebye
```

**Comment by devbranch-vitaliy** [comment]
We also can update postcss to the v7.0.36 but I agree that it's better to use 8.2.13.

**Comment by AoDev** [comment]
Man, I dont know why I dont get notified. I'll look into it. Thanks for reporting.

**Comment by AoDev** [comment]
I published a new release with updated dependencies. Thanks for using this package : )
