### ISSUE TITLE
postcss.plugin was deprecated in postcss8

### ISSUE THREAD

**Issue by wellenzhong** [AoDev/css-byebye#21]
when i use postcss8+css-byebye in my project, that warns:
```
css-byebye: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```
would u pls fix it up?

**Comment by AoDev** [comment]
Thanks for letting me know, I'll have a look when I have a moment.

**Comment by AoDev** [comment]
@wellenzhong I've published cssbyebye v4. It is using the new plugin api under the hood. The unit tests pass but it might be worth checking that you get the expected results.

**Comment by wellenzhong** [comment]
Great job! 
Thank you!

**Comment by AoDev** [comment]
Was resolved here: https://github.com/AoDev/css-byebye/pull/22
