### ISSUE TITLE
Allow css-byebye to be consumed in a PostCSS pipeline?

### ISSUE THREAD

**Issue by ben-eb** [AoDev/css-byebye#3]
This module should not wrap the PostCSS API, but instead expose itself as a processor that can be used in a pipeline along with other transforms:

```js
var postcss = require('postcss');
var css = 'a { font-size: 12px; } .hello .h1 { background: red } .world { color: blue }';

var output = postcss([
    require('css-byebye')({rulesToRemove: ['.world']}),
    require('autoprefixer')
]).process(css).css;

// do whatever with output
```

You can do this easily via the new `postcss.plugin()` API introduced in `4.1`, which enables us as plugin developers to develop consistent tools for the PostCSS ecosystem:

```js
var postcss = require('postcss');

module.exports = postcss.plugin('css-byebye', function (opts) {
    // use the options passed to you and return a transformation
    return function (css) {
        css.eachRule(function () { /* your logic here :) */ });
    }
});
```

That way we can use css-byebye alongside other processors to transform CSS many times in memory. :smile:

**Comment by ai** [comment]
@ben-eb is right

**Comment by AoDev** [comment]
@ben-eb @ai Hello, sorry for the late answer somehow I get to see your issue only now. I will check what you mention. If you want to send a PR it's more than welcomed, I have a lot of tasks these days. :)

**Comment by AoDev** [comment]
It should be working this way now: https://github.com/AoDev/css-byebye/pull/5
Let me know, I haven't added tests to see if it can be piped correctly.

**Comment by ben-eb** [comment]
Awesome. Thanks! :+1:
