### ISSUE TITLE
Not supported in PostCSS version 5.0.X

### ISSUE THREAD

**Issue by azat-io** [AoDev/css-byebye#6]
I get the following error when trying to use the plugin: "Your current PostCSS version is 5.0.2, but css-byebye uses 4.1.16. Perhaps this is the source of the error below".

Do you plan to release a new version of the plugin?

**Comment by AoDev** [comment]
Hello, sorry for the late answer. I did not see this issue. Sure, I'll make an update. I will check what changed since its a major release it might break stuff.

**Comment by azat-io** [comment]
Ok! Thanks for the answer!

**Comment by AoDev** [comment]
@azat-io I finally got time to do this. Let me know if you see any issue.
